version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: systemtest_production_django
    ports:
      - "80:5000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.django.production
      - ./.envs/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: systemtest_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.postgres

  redis:
    image: redis:6.0.9

  celeryworker:
    <<: *django
    ports:
      - "1"
    image: systemtest_production_django
    command: /start-celeryworker

  celerybeat:
    <<: *django
    ports:
      - "2"
    image: systemtest_production_django
    command: /start-celerybeat

  flower:
    <<: *django
    image: systemtest_production_django
    ports:
      - "5555:5555"
    command: /start-flower
