version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_staticfile_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: systemtest_production_django
    ports:
      - "80:5000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: systemtest_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    image: nginx:1.19
    volumes:
      - ./compose/production/nginx/nginx.conf:/ect/nginx/conf.d/default.conf
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"

  redis:
    image: redis:6.0.9

  celeryworker:
    <<: *django
    image: systemtest_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: systemtest_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: systemtest_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
