# Generated by Django 3.1.5 on 2021-05-20 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import systemtest.utils.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleStatus',
            fields=[
                ('id', models.SmallAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', systemtest.utils.models.CharFieldUpper(help_text='List element', max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'status',
                'db_table': 'people_status',
            },
        ),
        migrations.CreateModel(
            name='PeopleType',
            fields=[
                ('id', models.SmallAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', systemtest.utils.models.CharFieldUpper(help_text='List element', max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'db_table': 'people_type',
            },
        ),
        migrations.CreateModel(
            name='PeopleRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', systemtest.utils.models.CharFieldUpper(blank=True, default=None, help_text='Additional coment', max_length=50, null=True, verbose_name='Comment')),
                ('start', models.DateField(default=django.utils.timezone.now, help_text='Start Date', verbose_name='Start')),
                ('days', models.SmallIntegerField(default=1, help_text='Number of days that are granted with the requirement', verbose_name='Days')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Request DateTime', verbose_name='Created')),
                ('description', systemtest.utils.models.CharFieldUpper(blank=True, default=None, help_text='Description about the requirement', max_length=30, null=True, verbose_name='Description')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Update DateTime', verbose_name='Updated')),
                ('by_user', models.ForeignKey(help_text='User who makes the request', on_delete=django.db.models.deletion.PROTECT, related_name='by_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
                ('for_user', models.ForeignKey(help_text='User who receives the request', on_delete=django.db.models.deletion.PROTECT, related_name='for_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Requested for')),
                ('status', models.ForeignKey(default=1, help_text='Type of activity to be assigned', on_delete=django.db.models.deletion.PROTECT, to='people.peoplestatus', verbose_name='Activity Type')),
                ('type', models.ForeignKey(default=1, help_text='Type of requirement to be assigned', on_delete=django.db.models.deletion.PROTECT, to='people.peopletype', verbose_name='Requirement Type')),
            ],
            options={
                'verbose_name': 'requirement',
                'verbose_name_plural': 'requirements',
                'db_table': 'people_requirement',
            },
        ),
        migrations.CreateModel(
            name='PeopleHistory',
            fields=[
                ('comment', systemtest.utils.models.CharFieldUpper(blank=True, default=None, help_text='Additional coment', max_length=50, null=True, verbose_name='Comment')),
                ('start', models.DateField(default=django.utils.timezone.now, help_text='Start Date', verbose_name='Start')),
                ('days', models.SmallIntegerField(default=1, help_text='Number of days that are granted with the requirement', verbose_name='Days')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Request DateTime', verbose_name='Created')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier [ UUID ]', primary_key=True, serialize=False, unique=True, verbose_name='UID')),
                ('requirement', models.ForeignKey(help_text='Current requirement', on_delete=django.db.models.deletion.PROTECT, to='people.peoplerequirement', verbose_name='Requirement')),
                ('status', models.ForeignKey(default=1, help_text='Type of activity to be assigned', on_delete=django.db.models.deletion.PROTECT, to='people.peoplestatus', verbose_name='Activity Type')),
            ],
            options={
                'verbose_name': 'history',
                'verbose_name_plural': 'history',
                'db_table': 'people_requirement_history',
            },
        ),
    ]
