# Generated by Django 3.1.5 on 2021-01-15 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='user',
            field=models.ForeignKey(help_text='Usuario que realizo el cambio de estado en el requerimiento original', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='requestgroup',
            name='request_group_status',
            field=models.ForeignKey(default=1, help_text='Representa el estado de la piezas de este grupo', on_delete=django.db.models.deletion.PROTECT, to='pts.requestgroupstatus', verbose_name='Estado del grupo'),
        ),
        migrations.AddField(
            model_name='requestgroup',
            name='request_group_workspace',
            field=models.ForeignKey(default=1, help_text='El area donde esta el sistema', on_delete=django.db.models.deletion.PROTECT, to='pts.requestgroupworkspace', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='request',
            name='not_ncm_status',
            field=models.ForeignKey(blank=True, help_text='En caso que el estado sea malo, pero no se haya generado Tag', null=True, on_delete=django.db.models.deletion.CASCADE, to='pts.requestnotncmstatus', verbose_name='Motivos de tag faltante'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_group',
            field=models.ForeignKey(help_text='Grupo en el que se solicito', on_delete=django.db.models.deletion.PROTECT, to='pts.requestgroup', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_status',
            field=models.ForeignKey(default=1, help_text='Estado del requerimiento', on_delete=django.db.models.deletion.PROTECT, to='pts.requeststatus', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(help_text='Usuario que realizo el cambio de estado', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
