# Generated by Django 3.1.5 on 2021-03-16 13:43

import django.core.validators
from django.db import migrations, models
import systemtest.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('pts', '0002_auto_20210227_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestgroup',
            name='is_loaner',
            field=models.BooleanField(default=False, help_text="El sistema necesita piezas 'Loaner'", verbose_name='Loaner'),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='system_cell',
            field=systemtest.utils.models.CharFieldUpper(help_text='4 caracteres', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{4}$')], verbose_name='Celda del sistema'),
        ),
    ]
