# Generated by Django 3.1.5 on 2021-05-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts', '0002_auto_20210501_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestgroup',
            name='request_group_workspace',
            field=models.ForeignKey(default=1, help_text='Location where the system is', on_delete=django.db.models.deletion.PROTECT, to='pts.requestgroupworkspace', verbose_name='Location'),
        ),
    ]
