# Generated by Django 3.1.5 on 2021-02-17 17:58

import django.core.validators
from django.db import migrations
import systemtest.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('pts', '0002_auto_20210209_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='serial_number',
            field=systemtest.utils.models.CharFieldUpper(blank=True, default='', help_text='12 caracteres', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{12}$')], verbose_name='Numero de Seria [ SN ]'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='serial_number',
            field=systemtest.utils.models.CharFieldUpper(blank=True, default='', help_text='12 caracteres', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{12}$')], verbose_name='Numero de Seria [ SN ]'),
        ),
    ]
