# Generated by Django 3.1.4 on 2021-04-19 08:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import systemtest.utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pts', '0003_auto_20210316_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=systemtest.utils.models.CharFieldUpper(blank=True, default='', help_text='Comentario adicional', max_length=30, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='request',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de ultima transaccion', verbose_name='Actualizacion'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ncm_tag',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de Tag cuando la pieza es retornada como mala (8 caracteres numericos)', null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='request',
            name='part_number',
            field=systemtest.utils.models.CharFieldUpper(help_text='Numerp de parte (7 caracteres)', max_length=7, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{7}$', message='Solo 7 caracteres alfa-numericos')], verbose_name='Numero de parte [ PN ]'),
        ),
        migrations.AlterField(
            model_name='request',
            name='serial_number',
            field=systemtest.utils.models.CharFieldUpper(blank=True, default='', help_text='Numero de seria [opcional] (12 caracteres)', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{12}$', message='Solo 12 caracteres alfa-numericos')], verbose_name='Numero de Seria [ SN ]'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(help_text='Usuario que realizo la ultima transaccion', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='is_loaner',
            field=models.BooleanField(default=False, help_text="El sistema necesita piezas 'Loaner'.\n            Solo se debe usar cuando no deje reemplazar piezas normales", verbose_name='Loaner'),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='is_serialized',
            field=models.BooleanField(default=True, help_text='Numero de parte con serial.\n            Si no tiene serial solo es necesario registrar un numero de parte.\n            Los seriales solo pueden pertenecer a un numero de parte', verbose_name='Serializado'),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='is_vpd',
            field=models.BooleanField(default=False, help_text='Son piezas que se entregan al cambio', verbose_name='VPD o TPM'),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='part_description',
            field=systemtest.utils.models.CharFieldUpper(help_text='Nombre o descripcion de la pieza/parte (15 caracteres maximo)', max_length=15, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='part_number',
            field=systemtest.utils.models.CharFieldUpper(help_text='Numero de parte(s) del requerimiento original (7 caracteres)', max_length=7, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{7}$', message='Solo 7 caracteres alfa-numericos')], verbose_name='Part Number [ PN ]'),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='request_bay',
            field=systemtest.utils.models.CharFieldUpper(help_text='Bahia del usuario que requiere la pieaza (4 caracteres maximo)', max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{4}$', message='Solo 4 caracteres alfa-numericos')], verbose_name='Bahia TA'),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='system_cell',
            field=systemtest.utils.models.CharFieldUpper(help_text='Celda logica donde esta el sistema (7 caracteres maximo)', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{4}$', message='Solo 4 caracteres alfa-numericos')], verbose_name='Celda del sistema'),
        ),
        migrations.AlterField(
            model_name='requestgroup',
            name='system_number',
            field=systemtest.utils.models.CharFieldUpper(help_text='MFGN. Familia del Sistema (7 caracteres)', max_length=7, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{7}$', message='Solo 7 caracteres alfa-numericos')], verbose_name='Numero de sistema'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='comment',
            field=systemtest.utils.models.CharFieldUpper(blank=True, default='', help_text='Comentario adicional', max_length=30, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='part_number',
            field=systemtest.utils.models.CharFieldUpper(help_text='Numerp de parte (7 caracteres)', max_length=7, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{7}$', message='Solo 7 caracteres alfa-numericos')], verbose_name='Numero de parte [ PN ]'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='request',
            field=models.ForeignKey(help_text='Numero del requerimiento original con el estado actual', on_delete=django.db.models.deletion.PROTECT, related_name='request_history', to='pts.request', verbose_name='Requerimiento'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='serial_number',
            field=systemtest.utils.models.CharFieldUpper(blank=True, default='', help_text='Numero de seria [opcional] (12 caracteres)', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{12}$', message='Solo 12 caracteres alfa-numericos')], verbose_name='Numero de Seria [ SN ]'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='user',
            field=models.ForeignKey(help_text='Usuario que realizo la ultima transaccion', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
