# Generated by Django 3.1.5 on 2021-04-03 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210331_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shift',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
