# Generated by Django 3.1.4 on 2021-04-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210403_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Puesto del usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.job', verbose_name='Puesto'),
        ),
    ]
