# Generated by Django 3.1.5 on 2021-05-01 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitysystem',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='Usuario que realizo el cambio de estado', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='qualityhistory',
            name='quality_status',
            field=models.ForeignKey(blank=True, default=1, help_text='Estado del sistema', null=True, on_delete=django.db.models.deletion.PROTECT, to='quality.qualitystatus', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='qualityhistory',
            name='system',
            field=models.ForeignKey(help_text='Numero del requerimiento original, con el estado actual', on_delete=django.db.models.deletion.PROTECT, related_name='request_history', to='quality.qualitysystem', verbose_name='Requerimiento'),
        ),
        migrations.AddField(
            model_name='qualityhistory',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='Usuario que realizo el cambio de estado', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
