# Generated by Django 3.1.5 on 2021-05-13 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import systemtest.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_auto_20210501_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityhistory',
            name='quality_status',
            field=models.ForeignKey(blank=True, default=1, help_text='System status', null=True, on_delete=django.db.models.deletion.PROTECT, to='quality.qualitystatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='qualityhistory',
            name='system',
            field=models.ForeignKey(help_text='Original system', on_delete=django.db.models.deletion.PROTECT, related_name='system_history', to='quality.qualitysystem', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='qualitysystem',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='DateTime from last change', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='qualitysystem',
            name='product_line',
            field=systemtest.utils.models.CharFieldUpper(help_text='System type', max_length=20, verbose_name='Product Line'),
        ),
        migrations.AlterField(
            model_name='qualitysystem',
            name='quality_status',
            field=models.ForeignKey(blank=True, default=1, help_text='System status', null=True, on_delete=django.db.models.deletion.PROTECT, to='quality.qualitystatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='qualitysystem',
            name='system_number',
            field=systemtest.utils.models.CharFieldUpper(help_text='MFGN (7 chars)', max_length=7, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{7}$', message='Only 7 chars alpha-numeric')], verbose_name='System Number [ MFGN ]'),
        ),
        migrations.AlterField(
            model_name='qualitysystem',
            name='workunit_qty',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Quantity from same MFGN', null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(50)], verbose_name='WorkUnit Quantity'),
        ),
    ]
